from Datastructures.stacks.stackImplementation import *
s = Stack()
print(s.isEmpty())
s.push(4)
s.push('dog')
print s.peek()
print s.size()
print s.isEmpty()
s.push(8.4)
print(s.pop())
print(s.pop())
print(s.size())